spring:
  datasource:
    # Database URL
    url: jdbc:postgresql://localhost:5432/jwt_security

    # Database username
    username: postgres

    # Database password
    password: postgres

    # Database driver class
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Create, drop, or validate the database schema on startup
      ddl-auto: create-drop

    # Show SQL queries in the console
    show-sql: true

    properties:
      hibernate:
        # Format SQL queries for better readability
        format_sql: true

    # Specify the database type
    database: postgresql

    # Specify the Hibernate dialect for PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# application.yml
logging:
  level:
    root: INFO # Adjust the root log level as needed
    ir.hsadeghi.security.config.JwtAuthenticationFilter: DEBUG


application:
  security:
    jwt:
      secret-key: 29a898eedc3bff730347db73626c92fb8f0c32f2549d8bb847a2fd6217e69331
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604000000 # 7 days