# Database Configuration
spring:
  datasource:
    # Database URL
    url: jdbc:postgresql://localhost:5432/jwt_security

    # Database username
    username: postgres

    # Database password
    password: postgres

    # Database driver class
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Create, drop, or validate the database schema on startup
      ddl-auto: create-drop

    # Show SQL queries in the console
    show-sql: false

    properties:
      hibernate:
        # Format SQL queries for better readability
        format_sql: false

    # Specify the database type
    database: postgresql

    # Specify the Hibernate dialect for PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
# Adjust the log levels as needed for different packages/classes.
logging:
  level:
    root: INFO # Root log level is set to INFO
    ir.hsadeghi.security.config.JwtAuthenticationFilter: DEBUG # Detailed logs for JwtAuthenticationFilter


# Application-specific Configuration
application:
  security:
    jwt:
      # Secret key for JWT token signing and verification
      secret-key: 29a898eedc3bff730347db73626c92fb8f0c32f2549d8bb847a2fd6217e69331

      # Expiration time for JWT tokens (in milliseconds)
      expiration: 86400000 # 1 day

      # Configuration for JWT refresh tokens
      refresh-token:
        # Expiration time for refresh tokens (in milliseconds)
        expiration: 604000000 # 7 days
