package ir.hsadeghi.security.user;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor

@Entity
@Table(name = "_user") // Specifies the name of the database table

public class User {
    @Id // Marks the id field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies the generation strategy for the primary key
    private Integer id; // Unique identifier for the user

    private String firstname; // User's first name
    private String lastname; // User's last name
    private String email; // User's email address
    private String password; // User's password

    // Getters and setters are generated by Lombok's @Data annotation
}
